### PR TITLE
NEO-2021: adding test for percent encoding horizontal tab character in file object name

### PR DESCRIPTION
**Pull request by RachelTucker**
Also, fixed logical bug in existing tests that was causing the retrieval step to be skipped.

### CODE REVIEW

**Comment by rpmoore** [comment]
Why is there a Neo issue filed against the SDK?  Shouldn't that be an SDK issue?

**Comment by RachelTucker** [comment]
This test is actually verifying there is no issue with the SDK.

**Comment by rpmoore** [comment]
> 
> 
> This test is actually verifying there is no issue with the SDK.

It just seems odd for it to reference a neo issue.

**Comment by RachelTucker** [comment]
I'll tidy up my commit messages and titles in the future.

**Pull request merged**
